Add Translation to Thai, Burmese, Swahili
lovasoa/whitebophir pull request #222
Opened 2021-09-23 13:05 UTC by lisandi

And one addition to English Missing Correction Fluid

<sub>
By opening a pull request, I certify that I hold the intellectual property of the code I am submitting,
and I am granting the initial authors of WBO a perpetual, worldwide, non-exclusive, royalty-free, and irrevocable license to this code.
</sub>

2021-09-23 15:28 UTC, lovasoa requested changes
Awesome, thank you very much for this contribution ! Do you speak all of these languages natively ?

I found a few problems with the HTML tags

2021-09-23 15:28 UTC, lovasoa commented on server/translations.json
> +    "white-out": "Correction fluid",
Already defined on line 43

2021-09-23 15:28 UTC, lovasoa commented on server/translations.json
> +    "click_to_zoom": "ချဲ့ရန်နှိပ်ပါ \ n shift key ကိုကိုင်ထားပြီးချဲ့ရန်နှိပ်ပါ",
```suggestion
    "click_to_zoom": "ချဲ့ရန်နှိပ်ပါ\nshift key ကိုကိုင်ထားပြီးချဲ့ရန်နှိပ်ပါ",
```

2021-09-23 15:28 UTC, lovasoa commented on server/translations.json
> +    "public_board_description": " အဆိုပါ <b> အများသုံး whiteboard </b> ကိုမည်သူမဆိုဖွင့်နိုင်ပါသည်။ ၎င်းသည်အမည်မသိသူစိမ်းများနှင့်သင်ဆေးသုတ်နိုင်သောပျော်ရွှင်စရာ၊ ရှုပ်ထွေးသောရှုပ်ထွေးမှုတစ်ခုဖြစ်သည်
```suggestion
    "public_board_description": "အဆိုပါ <b> အများသုံး whiteboard </b> ကိုမည်သူမဆိုဖွင့်နိုင်ပါသည်။ ၎င်းသည်အမည်မသိသူစိမ်းများနှင့်သင်ဆေးသုတ်နိုင်သောပျော်ရွှင်စရာ၊ ရှုပ်ထွေးသောရှုပ်ထွေးမှုတစ်ခုဖြစ်သည်။",
```

2021-09-23 15:28 UTC, lovasoa commented on server/translations.json
> +    "click_to_zoom": "Bonyeza kuvuta ndani \ n Shikilia kitufe cha kuhama na ubofye ili kukuza",
```suggestion
    "click_to_zoom": "Bonyeza kuvuta ndani\nShikilia kitufe cha kuhama na ubofye ili kukuza",
```

2021-09-23 15:28 UTC, lovasoa commented on server/translations.json
> +    "introduction_paragraph": "WBO သည် <a href = \" https: //github.com/lovasoa/whitebophir \ "title = \" ဘီယာမပါ၊ လွတ်လပ်စွာပြောဆိုခွင့်၊ အခမဲ့ဖြစ်သည်။ ဤဆော့ဝဲကို AGPL လိုင်စင်အောက်တွင်ထုတ်ဝေသည်။ \
```suggestion
    "introduction_paragraph": "WBO သည် <a href=\"https://github.com/lovasoa/whitebophir\" title=\"ဘီယာမပါ၊ လွတ်လပ်စွာပြောဆိုခွင့်၊ အခမဲ့ဖြစ်သည်။ ဤဆော့ဝဲကို AGPL လိုင်စင်အောက်တွင်ထုတ်ဝေသည်။\"> အခမဲ့နှင့်ပွင့်လင်းသောအရင်းအမြစ် </a> ပူးပေါင်းဆောင်ရွက်သည့်အွန်လိုင်း whiteboard ကိုအသုံးပြုသူများအား virtual whiteboard ကြီးတစ်ခုပေါ်တွင်တစ်ချိန်တည်းဆွဲခွင့်ပြုသည်။ whiteboard ကိုအသုံးပြုသူများအားလုံးအတွက်အချိန်နှင့်တပြေးညီအဆင့်မြှင့်တင်ခဲ့သည်။ ၎င်း၏အကြောင်းအရာကိုသိမ်းဆည်းထားသည်။ ၎င်းကိုအနုပညာ၊ ဖျော်ဖြေရေး၊ ဒီဇိုင်း၊ သင်ကြားမှုနှင့်သင်ကြားမှုကဲ့သို့သောအသုံးချမှုမျိုးစုံအတွက်အသုံးပြုနိုင်သည်",
```

2021-09-23 15:28 UTC, lovasoa commented on server/translations.json
> +    "introduction_paragraph": "WBO ni <a href = \" https: //github.com/lovasoa/whitebophir \ "title = \" Huru kwa maana ya kusema bure, sio bia ya bure. Programu hii imechapishwa chini ya leseni ya A
```suggestion
    "introduction_paragraph": "WBO ni <a href=\"https: //github.com/lovasoa/whitebophir\" title=\"Huru kwa maana ya kusema bure, sio bia ya bure. Programu hii imechapishwa chini ya leseni ya AGPL. Yaliyomo yamehifadhiwa. Inaweza kutumika kwa matumizi anuwai, kama sanaa, burudani, kubuni, kufundisha na kufundisha.",
```

The `<a` tag opens and never closes in this translation

2021-09-23 15:28 UTC, lovasoa commented on server/translations.json
> +    "click_to_zoom": "คลิกเพื่อซูมเข้า \ nกดปุ่ม shift ค้างไว้แล้วคลิกเพื่อซูมออก",
```suggestion
    "click_to_zoom": "คลิกเพื่อซูมเข้า\nกดปุ่ม shift ค้างไว้แล้วคลิกเพื่อซูมออก",
```

2021-09-23 15:28 UTC, lovasoa commented on server/translations.json
> +    "introduction_paragraph": "WBO เป็น <a href = \" https: //github.com/lovasoa/whitebophir \"title = \" ฟรีในแง่ของการพูดฟรี ไม่ใช่เบียร์ฟรี ซอฟต์แวร์นี้เผยแพร่ภายใต้ลิขสิทธิ์ AGPL \"> ฟรีและโอเพ่น
```suggestion
    "introduction_paragraph": "WBO เป็น <a href=\"https://github.com/lovasoa/whitebophir\" title=\"ฟรีในแง่ของการพูดฟรี ไม่ใช่เบียร์ฟรี ซอฟต์แวร์นี้เผยแพร่ภายใต้ลิขสิทธิ์ AGPL\">ฟรีและโอเพ่นซอร์ส</a> ไวท์บอร์ดออนไลน์สำหรับการทำงานร่วมกันที่อนุญาตให้ผู้ใช้จำนวนมากวาดบนไวท์บอร์ดเสมือนจริงขนาดใหญ่พร้อมกัน ไวท์บอร์ดได้รับการอัปเดตตามเวลาจริงสำหรับผู้ใช้ทั้งหมดและ เนื้อหาจะถูกบันทึกไว้ . สามารถใช้งานได้หลากหลายเช่นศิลปะ, บันเทิง, การออกแบบ, การสอนและการสอน ",
```

2021-09-23 15:28 UTC, lovasoa commented on server/translations.json
> +    "public_board_description": " ใครๆ ก็เปิด <b> กระดานไวท์บอร์ดสาธารณะ </b> ได้ เป็นเรื่องที่น่ายินดีและไม่เป็นระเบียบ ซึ่งคุณสามารถวาดภาพร่วมกับคนแปลกหน้าที่ไม่ระบุชื่อได้ ทุกๆ อย่างในที่นี้เป็นเพ
```suggestion
    "private_board_description": "คุณสามารถสร้าง <b>ไวท์บอร์ดส่วนตัว</b> ด้วยชื่อแบบสุ่มที่สามารถเปิดได้ด้วยลิงก์เท่านั้น ใช้ตัวเลือกนี้หากคุณต้องการแบ่งปันข้อมูลส่วนตัว",
    "public_board_description": "ใครๆ ก็เปิด <b>กระดานไวท์บอร์ดสาธารณะ</b> ได้ เป็นเรื่องที่น่ายินดีและไม่เป็นระเบียบ ซึ่งคุณสามารถวาดภาพร่วมกับคนแปลกหน้าที่ไม่ระบุชื่อได้ ทุกๆ อย่างในที่นี้เป็นเพียงชั่วคราวเท่านั้น",
```

2021-09-23 15:28 UTC, lovasoa commented on server/translations.json
> +    "named_private_board_description": "คุณยังสามารถสร้าง <strong> ไวท์บอร์ดส่วนตัวที่มีชื่อ </strong> ด้วย URL ที่กำหนดเองได้ ใครก็ตามที่รู้จักชื่อนี้สามารถเข้าถึงได้",
```suggestion
    "named_private_board_description": "คุณยังสามารถสร้าง <strong>ไวท์บอร์ดส่วนตัวที่มีชื่อ</strong> ด้วย URL ที่กำหนดเองได้ ใครก็ตามที่รู้จักชื่อนี้สามารถเข้าถึงได้",
```

2021-09-23 15:28 UTC, lovasoa commented on server/translations.json
> +    "named_private_board_description": "မင်းစိတ်ကြိုက် url တစ်ခုနဲ့ <strong> ကိုယ်ပိုင် whiteboard တစ်ခုကိုလည်းသင်ဖန်တီးနိုင်သည်။ နာမည်သိသူတိုင်း၎င်းကိုသုံးနိုင်သည်။ ",
There is a `</strong>` missing here

2021-09-23 15:28 UTC, lovasoa commented on server/translations.json
> +    "public_board_description": " Bodi nyeupe ya umma </b> inaweza kufunguliwa na mtu yeyote. Ni fujo yenye furaha, isiyo na mpangilio ambapo unaweza kupaka rangi na wageni wasiojulikana. Kila kitu h
There is a `</b>` without a `<b>` here

2021-09-23 23:41 UTC, lisandi commented
Hi Ophir LOJKINE
Unfortunately not all those languages even I would wish too but I am good
at motivating others to help me :-)
I run a company in Thailand and work to make All Inclusive Montessori
Education for All a reality and that involves activities in Africa
(Tanzania, Uganda, Ruanda, and DRC for now) and so I practice the language
skills but still far from perfect. But as my father who was a great leader
in a company too once said after a fire destroyed the work of years which
now had to be rebuilt in less than one year to meet the deadlines and he
worked through all day - no holidays - from early morning to very late and
even on Saturday Sunday- simply working through for nearly one year. I
asked him why he did that and he said to me that if he as a leader would
have quitted with sickness or "I can no more" all others would have
considered that too and the project would never have met the deadline. So
he had to give THE example that it is worth giving really all to meet the
goal. I try to follow that advice and my goal is "All Inclusive Montessori
Education for All" and to meet that goal we need to motivate people not
only to donate time and funds but also themselves - and often also their
peers - to make that happen. In the case of the translations, it is simply
necessary to have them as otherwise, the people won't understand and then
not use the online tools - But actually, it will be the provided
online tools which will help us to reach the goals and actually to make it
possible thanks worldwide cooperation tools. In the rich world, we have
tons of expensive private Montessori Schools and in the poor world we have
none of them - well also some pretty expensive ones - but what is needed is
FREE Montessori Education for All - so we need to train teachers at first
place - but to become a Montessori teacher is incredible expensive too as
the name "Montessori" sells pretty good. I like to provide FREE resources -
FREE Training and of course a highly qualification certificate which is
affordable for every teacher who is able to also finance a smartphone.
Thanks to tools like WBO we have now tools to make that happen! ;-) - and
we use it also on other sites too i.e. for Churches and Communities - as
those will hopefully help us too by spreading the word, raising funds, and
motivating others.

And the Burmese - well my grandson is going to a Good Shepherd School here
in Phuket/Thailand which takes care of Burmese Migrant Children. He is
officially Homeschooling but going there for socializing and of course, for
learning - even he is 100%, Thai. But I decided to send him there because
that school knows how to deal with his ADHD Problems pretty well and they
don't beat the children - like they still do in many Thai schools. So here
are my Burmese Helpers ;-) beside my Thai Staff in the company itself. The
Swahili was helped by 2 people who cross-checked it from Tanzania and
Uganda.

Yeah with the HTML I actually had a bit of a problem as we edited as
described directly on Github which was probably not a good idea and then we
saved it and saw in the green areas diffs that there might be problems but
could not find them - That is my problem with especially Thai and Burmese
as here the letters sometimes get written from left to right but also from
right to left in some cases - i.e. My wife is called Urai but when you
would read the Thai Letters letter by better like you are used to in
western world then you would read Uair with the r at the end! - อุไร - the
first bug letter here has actually NO sound and gets used when a word
starts with a Vowel. The "U" is that tiny little Hook below that big first
letter. - The second letter is the "ai" (pronounced like a German "ai" "a
meted to i") and the last letter is the "r". For me it is always a headache
to find out the words in Thai and Burmese as in both languages they have no
separation of words either ;-) I, therefore, prefer languages like Russian
or Swahili where you can separate the words and that makes it much easier
to understand and learn them. - The process in our company is that I
usually start a translation to a language and then ask them to help me to
get it actually done ;-) completely - while I sit often hours to find and
write the first part.e. 10% and they do the rest 90% in no time at all :-)
But without me starting they would never do it at all! - Well and often
they then correct me of course pointing out the writing errors in my 10%
hahaha. Here in Phuket I can find nearly all languages of the world -
really a great place and even in our company we are very multilingual too.

Keep up your good work as it is doing and enabling great things to come.

Thanks a lot!
tools

With kind regards,
*
<https://about.me/andibecker?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>
Andreas Becker about.me/andibecker
<https://about.me/andibecker?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>
**LisAndi Co. Ltd.*, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Phone: +66 (0)76 530 595
GTalk/Facetime/eMail:  ***@***.***
Mobile/WhatsApp/Line: +66 (0)81 606 3378
Facebook/Line/Messenger: andibecker
Skype: lisandi
--------------------------------------------------



On Thu, Sep 23, 2021 at 10:28 PM Ophir LOJKINE ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Awesome, thank you very much for this contribution ! Do you speak all of
> these languages natively ?
>
> I found a few problems with the HTML tags
> ------------------------------
>
> In server/translations.json
> <https://github.com/lovasoa/whitebophir/pull/222#discussion_r714896149>:
>
> > @@ -77,6 +77,7 @@
>      "text": "Text",
>      "tools": "Tools",
>      "view_source": "Source code on GitHub",
> +    "white-out": "Correction fluid",
>
> Already defined on line 43
> ------------------------------
>
> In server/translations.json
> <https://github.com/lovasoa/whitebophir/pull/222#discussion_r714896684>:
>
> > @@ -273,6 +274,46 @@
>      "white-out": "修正液",
>      "zoom": "拡大・縮小"
>    },
> +  "my": {
> +    "board_name_placeholder": "ဝှိုက်ဘုတ်အမည် ... ",
> +    "circle": "စက်ဝိုင်း",
> +    "click_to_toggle": "toggle ကိုနှိပ်ပါ",
> +    "click_to_zoom": "ချဲ့ရန်နှိပ်ပါ \ n shift key ကိုကိုင်ထားပြီးချဲ့ရန်နှိပ်ပါ",
>
> ⬇️ Suggested change
>
> -    "click_to_zoom": "ချဲ့ရန်နှိပ်ပါ \ n shift key ကိုကိုင်ထားပြီးချဲ့ရန်နှိပ်ပါ",
> +    "click_to_zoom": "ချဲ့ရန်နှိပ်ပါ\nshift key ကိုကိုင်ထားပြီးချဲ့ရန်နှိပ်ပါ",
>
> ------------------------------
>
> In server/translations.json
> <https://github.com/lovasoa/whitebophir/pull/222#discussion_r714897164>:
>
> > +    "grid": "ဇယားကွက်",
> +    "hand": "လက်",
> +    "download": "ဒေါင်းလုပ်",
> +    "index_title": "WBO မှကြိုဆိုပါသည်",
> +    "introduction_paragraph": "WBO သည် <a href = \" https: //github.com/lovasoa/whitebophir \ "title = \" ဘီယာမပါ၊ လွတ်လပ်စွာပြောဆိုခွင့်၊ အခမဲ့ဖြစ်သည်။ ဤဆော့ဝဲကို AGPL လိုင်စင်အောက်တွင်ထုတ်ဝေသည်။ \ "> အခမဲ့နှင့်ပွင့်လင်းသောအရင်းအမြစ် </a> ပူးပေါင်းဆောင်ရွက်သည့်အွန်လိုင်း whiteboard ကိုအသုံးပြုသူများအား virtual whiteboard ကြီးတစ်ခုပေါ်တွင်တစ်ချိန်တည်းဆွဲခွင့်ပြုသည်။ whiteboard ကိုအသုံးပြုသူများအားလုံးအတွက်အချိန်နှင့်တပြေးညီအဆင့်မြှင့်တင်ခဲ့သည်။ ၎င်း၏အကြောင်းအရာကိုသိမ်းဆည်းထားသည်။ ၎င်းကိုအနုပညာ၊ ဖျော်ဖြေရေး၊ ဒီဇိုင်း၊ သင်ကြားမှုနှင့်သင်ကြားမှုကဲ့သို့သောအသုံးချမှုမျိုးစုံအတွက်အသုံးပြုနိုင်သည်",
> +    "keyboard_shortcut": "ကီးဘုတ်ဖြတ်လမ်း",
> +    "loading": "တင်နေသည်",
> +    "menu": "မီနူး",
> +    "mousewheel": "ကြွက်ဘီး",
> +    "mover": "ပြောင်း",
> +    "named_private_board_description": "မင်းစိတ်ကြိုက် url တစ်ခုနဲ့ <strong> ကိုယ်ပိုင် whiteboard တစ်ခုကိုလည်းသင်ဖန်တီးနိုင်သည်။ နာမည်သိသူတိုင်း၎င်းကိုသုံးနိုင်သည်။ ",
> +    "opacity": "အလင်းအမှောင်",
> +    "open_public_board": "အများသုံး whiteboard သို့သွားပါ",
> +    "pencil": "ဘောပင်",
> +    "private_board_description": "လင့်ခ်တစ်ခုသာဖွင့်နိုင်သော [...]

2021-09-24 21:42 UTC, lovasoa commented
It sounds like you are doing a lot of good work, congratulations.

For the translations, I tried to fix the markup myself, but it's hard to do so without understanding the text myself.

I'll merge this for now, but can you please have the native speakers check the result on the live website, and open new pull requests if anything seems wrong ?

2021-09-24 21:42 UTC, merged